version: '3.8'

services:
  order-service:
    image: spotq-order-service:latest
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      
      - INFISICAL_TOKEN= ${INFISICAL_TOKEN}
    restart: unless-stopped